name: mobilemoneytanzania
description: "A Simple Flutter package that integrates all mobile money providers in Tanzania. Included providers are Airtel,Vodacom,Halotel,Mixx and TTCL"
version: 0.0.1
homepage: "https://github.com/PhilipMuze/mobilemoney_tanzania"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

